name: SkyblockCore
version: '2.1'
main: jefry.plugin.skyblockCore.SkyblockCore
api-version: '1.21'
commands:
  island:
    description: Manage your island in Skyblock.
    usage: /island <create|join|upgrade|leave|stats|shop|pos1|pos2>
    aliases: [isl]